class _BotCommands:
    def __init__(self):
        self.StartCommand = 'mulai'
        self.MirrorCommand = 'cermin'
        self.UnzipMirrorCommand = 'cerminunzip'
        self.ZipMirrorCommand = 'cerminzip'
        self.ZipWatchCommand = 'nontonzip'
        self.QbMirrorCommand = 'cerminqb'
        self.QbUnzipMirrorCommand = 'qbunzipmirror'
        self.QbZipMirrorCommand = 'qbcerminzip'
        self.CancelMirror = 'batal'
        self.CancelAllCommand = 'batalkan'
        self.ListCommand = 'daftar'
        self.SearchCommand = 'cari'
        self.StatusCommand = 'status'
        self.AuthorizedUsersCommand = 'pengguna'
        self.AuthorizeCommand = 'mengizinkan'
        self.UnAuthorizeCommand = 'tidaksah'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping'
        self.RestartCommand = 'reboot'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'tolong'
        self.LogCommand = 'log'
        self.SpeedCommand = 'aducepat'
        self.CloneCommand = 'ganda'
        self.CountCommand = 'hitung'
        self.WatchCommand = 'nonton'
        self.DeleteCommand = 'hapus'
        self.UsageCommand = 'sisakuota'
        self.MediaInfoCommand = 'mediainfo'
        self.ShellCommand = 'cmd'
        self.ExecHelpCommand = 'tolongexec'
        self.LeechSetCommand = 'setleech'
        self.SetThumbCommand = 'setthumb'
        self.LeechCommand = 'leech'
        self.UnzipLeechCommand = 'unzipleech'
        self.ZipLeechCommand = 'zipleech'
        self.QbLeechCommand = 'qbleech'
        self.QbUnzipLeechCommand = 'qbunzipleech'
        self.QbZipLeechCommand = 'qbzipleech'
        self.LeechWatchCommand = 'leechwatch'
        self.LeechZipWatchCommand = 'leechzipwatch'


BotCommands = _BotCommands()
